/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// ---------------------------------------
// THIS FILE IS AUTOGENERATED; DO NOT EDIT
//
// This file is created from version.h.in - by hand for now but automate with Python, not cmake
// ---------------------------------------

#ifndef _PICO_VERSION_H
#define _PICO_VERSION_H

#define PICO_SDK_VERSION_MAJOR    (2)
#define PICO_SDK_VERSION_MINOR    (2)
#define PICO_SDK_VERSION_REVISION (0)
#define PICO_SDK_VERSION_STRING   "pico-sdk 2.2.0"

#endif
